#!/bin/bash
#$ -N masking
#$ -q default.q
#$ -cwd
#$ -e logs/$JOB_NAME-$JOB_ID.err
#$ -o logs/$JOB_NAME-$JOB_ID.out
module load python
python3 /homedtic/gmarti/CODE/img-mri-processing/MRI_processing/createmask.py --template_mask /homedtic/gmarti/DATA/Data/icbm_avg_152_t1_tal_nlin_symmetric_VI_mask.nii --in_dir /homedtic/gmarti/DATA/Data/ADNI_Affine1_SdBaseline/ --out_dir /homedtic/gmarti/DATA/Data/ADNI_Affine1_SdBaseline_masked/ --img_suffix Warped.nii.gz --dilate --size 3
